spring:
  profiles:
    active: dev
# 配置多套生产环境
---
spring:
  profiles: dev
## 配置项目虚拟路径
server:
  servlet:
    context-path: /07swagger_sb
---
spring:
  profiles: prod
## 配置项目虚拟路径
server:
  servlet:
    context-path: /07swagger_sb